import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarMenu } from "@/components/ui/sidebar";
import { LayoutTransition } from "@/components/layout-transition";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div className="hidden sm:block">
            <SidebarMenu />
          </div>
          <main className="w-full px-4">
            <LayoutTransition
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              {children}
            </LayoutTransition>
          </main>
        </div>
      </body>
    </html>
  );
}
